print(50*'=')
print('               TABUADA ELETRÔNICA')
print(50*'=')
print('')
n = int(input('Digite um número para que eu possa mostrar a sua tabuada: '))
print('')
print(50*'=')
print('')
print(' 1  x {:2} = {:2}'.format(n, (n*1)), end='  |  ')
print(' 6  x {:2} = {:2}'.format(n, (n*6)))
print(' 2  x {:2} = {:2}'.format(n, (n*2)), end='  |  ')
print(' 7  x {:2} = {:2}'.format(n, (n*7)))
print(' 3  x {:2} = {:2}'.format(n, (n*3)), end='  |  ')
print(' 8  x {:2} = {:2}'.format(n, (n*8)))
print(' 4  x {:2} = {:2}'.format(n, (n*4)), end='  |  ')
print(' 9  x {:2} = {:2}'.format(n, (n*9)))
print(' 5  x {:2} = {:2}'.format(n, (n*5)), end='  |  ')
print(' 10 x {:2} = {:2}'.format(n, (n*10)))
print('')
print(50*'=')

